vertex_project_dev: "my-gcp-project-dev"
vertex_project_staging: "my-gcp-project-staging"
vertex_project_prod: "my-gcp-project-prod"
resource_suffix: "default"

dev:
  
  prediction_type: "batch"  # "batch" for batch prediction, "endpoint" for deploy+smoke-test+undeploy
  endpoint_name: "turbo-prediction-endpoint"
  model_name: "xgb_regressor"
  vertex_location: "europe-west2"
  bq_location: "europe-west2"
  bq_dataset_id: "chicago_taxi_trips"
  bq_table_id: "taxi_trips"


  training:
    label: "total_fare"
    n_estimators: 200
    early_stopping_rounds: 10
    objective: "reg:squarederror"
    booster: "gbtree"
    learning_rate: 0.3
    min_split_loss: 0
    max_depth: 6
    train_test_split_size: 0.2
    train_valid_split_size: 0.25
    train_test_random_state: 1
    train_valid_random_state: 1

  scheduler:
    enable_training_scheduler: false
    training_cron: "0 0 * * 4"  # https://crontab.guru/
    training_max_concurrent_run_count: 1
    training_max_run_count: 0  # Put 0 for infinite

    enable_prediction_scheduler: false
    prediction_cron: ""  # https://crontab.guru/
    prediction_max_concurrent_run_count: 1
    prediction_max_run_count: 0  # Put 0 for infinite
  alert_emails:
    - "roberta.nwokonko@datatonic.com"
  notification_channels: []
  monitoring:
    enable: false
    monitor_interval_hours_cron_job: "0 0 * * *"
    monitor_window_hours: 24
    default_drift_threshold: 0.3
    monitored_feature_names:
      - mileage
      - photos_damage_count
    monitored_prediction_field_names:
      - prediction_value
    notification_emails:
      - "roberta.nwokonko@datatonic.com"

staging:

  prediction_type: "batch"  # "batch" for batch prediction, "endpoint" for deploy+smoke-test+undeploy
  endpoint_name: "turbo-prediction-endpoint"
  vertex_location: "europe-west2"
  bq_location: "europe-west2"
  bq_dataset_id: "ml_dataset"
  bq_table_id: "taxi_trips"


  training:
    label: "total_fare"
    n_estimators: 200
    early_stopping_rounds: 10
    objective: "reg:squarederror"
    booster: "gbtree"
    learning_rate: 0.3
    min_split_loss: 0
    max_depth: 6
    train_test_split_size: 0.2
    train_valid_split_size: 0.25
    train_test_random_state: 1
    train_valid_random_state: 1
    
  alert_emails: []
  notification_channels: []

  scheduler:
    enable_training_scheduler: false
    training_cron: "0 0 * * 4"  # https://crontab.guru/
    training_max_concurrent_run_count: 1
    training_max_run_count: 0  # Put 0 for infinite

    enable_prediction_scheduler: false
    prediction_cron: ""  # https://crontab.guru/
    prediction_max_concurrent_run_count: 1
    prediction_max_run_count: 0  # Put 0 for infinite

  alert_emails:
    - "roberta.nwokonko@datatonic.com"
  notification_channels: []

  monitoring:
    enable: false
    monitor_interval_hours_cron_job: "0 0 * * *"
    monitor_window_hours: 24
    default_drift_threshold: 0.3
    monitored_feature_names:
      - mileage
      - photos_damage_count
    monitored_prediction_field_names:
      - prediction_value
    notification_emails:
      - "roberta.nwokonko@datatonic.com"

prod:

  prediction_type: "endpoint"  # "batch" for batch prediction, "endpoint" for deploy+smoke-test+undeploy
  endpoint_name: "turbo-prediction-endpoint"
  vertex_location: "europe-west2"
  bq_location: "europe-west2"
  bq_dataset_id: "ml_dataset"
  bq_table_id: "taxi_trips"

  scheduler:
    enable_training_scheduler: false
    training_cron: "0 0 * * 4"  # https://crontab.guru/
    training_max_concurrent_run_count: 1
    training_max_run_count: 0  # Put 0 for infinite

    enable_prediction_scheduler: false
    prediction_cron: ""  # https://crontab.guru/
    prediction_max_concurrent_run_count: 1
    prediction_max_run_count: 0  # Put 0 for infinite

  alert_emails:
    - "roberta.nwokonko@datatonic.com"
  notification_channels: []
  
  monitoring:
    enable: false
    monitor_interval_hours_cron_job: "0 0 * * *"
    monitor_window_hours: 24
    default_drift_threshold: 0.3
    monitored_feature_names:
      - mileage
      - photos_damage_count
    monitored_prediction_field_names:
      - prediction_value
    notification_emails:
      - "roberta.nwokonko@datatonic.com"
